
spring:
  main:
    banner-mode: off


  datasource:
    url: jdbc:postgresql://localhost:5432/online_avia_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tatu2022

  jpa:
    hibernate:
      ddl-auto: create #update  , none
      show-sql: true
      properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect

      server:
      port: 8080















